name: Compile blueprint

on:
  push:
    branches:
      - {| master_branch |} # Trigger on pushes to the default branch
  workflow_dispatch:        # Allow manual triggering of the workflow from the GitHub Actions interface

# Cancel previous runs if a new commit is pushed to the same PR or branch
concurrency:
  group: ${{ github.ref }}  # Group runs by the ref (branch or PR)
  cancel-in-progress: true  # Cancel any ongoing runs in the same group

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read          # Read access to repository contents
  pages: write            # Write access to GitHub Pages
  id-token: write         # Write access to ID tokens
  issues: write           # Write access to issues
  pull-requests: write    # Write access to pull requests

jobs:
  build_project:
    runs-on: ubuntu-latest
    name: Build project
    steps:
      - name: Cleanup to free disk space
        uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be # v1.3.0
        with:
          tool-cache: false
          android: true
          dotnet: false
          haskell: false
          large-packages: false
          docker-images: false
          swap-storage: false

      - name: Checkout project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Build and lint project
        uses: leanprover/lean-action@434f25c2f80ded67bba02502ad3a86f25db50709 # 2025-07-02
        with:
          build: true
          lint: true
          mk_all-check: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz libgraphviz-dev
          pip install git+https://github.com/rwst/leanblueprint-light.git
      - name: Build Blueprint
        run: |
          leanblueprint-light web
          leanblueprint-light checkdecls

      - name: Copy artifacts to site directory
        run: |
          mkdir -p _site/blueprint
          cp -r blueprint/web/* _site/blueprint/

      - name: Upload to GitHub Pages
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: _site/

  deploy:
    if: github.event_name == 'push'
    needs: build_project
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5